### PR TITLE
Support the overriden methods respecting superclass methods annotations.

### PR DESCRIPTION
**Pull request by smecsia**
Supporting the correct resource methods overriding. It may be useful if you use generified superclass. At the moment the following example will be generated incorrectly (Entity will be taken as a model, which is not correct): 

```java
// UsersResource.java
@Path("/users")
public class UsersResource extends BasicResource<User> {
    @Override
    public List<User> findAll() {
        return super.findAll();
    }
}

// BasicResource.java
public abstract class BasicResource<Entity> {
    @GET
    @Path("/{parentId}")
    public List<Entity> findAll() {
        return getDAO().findAll();
    }
}
```

P.S. By the way, it would be much better not to override such methods at all. But I'm not sure it is possible to detect the actual type arguments for the superclass correctly within the doclet..

### CODE REVIEW

**Comment by smecsia** [comment]
Guys, I've added the test for this PR, and it passes. Your build seems to be broken because of other reasons.

**Comment by smecsia** [comment]
I've added some changes to .travis.yml to change build behaviour. See the explanation [here](http://docs.travis-ci.com/user/pull-requests/).

**Comment by conorroche** [comment]
hey thanks a lot, i'm really busy with work commitments at the moment so haven't had a chance to look at this but will try and look at it as soon as I can.

**Comment by conorroche** [comment]
@smecsia Not all features were supported on superclass resource methods following your pull request, I have now extended the test case and code to support more of the features like response messages, min max default values, produces, consumes etc

**Pull request merged**
